### ISSUE TITLE
Configurable method completion mode

### ISSUE THREAD

**Issue by gavr123456789** [Prince781/vala-language-server#111]
This setting was present in VLS B. And it is also present in almost all other languages plugs.   
I'm very used to it.  
I also think this can be improved, if a function is called in an empty context(not as an argument to another function), you can also automatically put a semicolon after brackets. I think so does the rider from intellij. But of course this is probably quite difficult.
![изображение](https://user-images.githubusercontent.com/30507409/80750246-6789da00-8b30-11ea-8f08-b1fec82855d6.png)

**Comment by Prince781** [comment]
Right now, VLS doesn't complete function brackets at all because I'm aware that there are different preferences for having a space before the brackets for different projects. (Geary, for example, prefers no spaces.)

If I implement it, then I'd have to have a default behavior, and that would mean that for editors that don't have a VLS plugin (vim, IntelliJ, and anything else not VSCode or GNOME Builder currently), VLS might always be doing the wrong thing and the user would have no way to fix that.

If VLS is going to do this, it should be smart enough to do the right thing based on the formatting used in the rest of the document.

**Comment by gavr123456789** [comment]
> If I implement it, then I'd have to have a default behavior, and that would mean that for editors that don't have a VLS plugin (vim, IntelliJ, and anything else not VSCode or GNOME Builder currently), VLS might always be doing the wrong thing and the user would have no way to fix that.  
  
Why? Just don't add brackets automatically in the default settings, that's all. The users will choose which option suits them, with or without a space. But it just disabled by default.

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/81704413-6af95b80-9476-11ea-975f-5451cafaad10.png)
Screen from VLS B.  
P.S. Log level and path also good ideas.

**Comment by gavr123456789** [comment]
After 3 weeks of working with C# in Rider and returning to Vala, I realized how much this feature is missing. My fingers are literally used to automatically appearing brackets with ; after auto-completion at the level of muscle memory.  
  
Now I think that the user should be given the following 2 types of options:   
1) Method completion mode:  
nothing;  
with a space;  
without a space;  

2) Add semicolon:  
Yes;  
No;

**Comment by gavr123456789** [comment]
How I think it needs to look
![Peek 2020-07-19 13-47](https://user-images.githubusercontent.com/30507409/87873023-93498d00-c9c6-11ea-863b-c06686065256.gif)

**Comment by Prince781** [comment]
The problem here is: what happens if you want to write a chain of invocations? For example:

```vala
var sb = new StringBuilder();
sb.append("foo")
    .append("bar")
    .append("manam");
```

or more likely:
```vala
var ordered_rands = new Gee.ArrayList<int>.wrap({40, 3, 10, 4, 100, -1, 3, -5})
    .map(x => /* ... */)
    .chop(2)
    .order_by((x, y) => x - y);
    // etc
```

Then each time you complete a method you would have to delete a semicolon. There are two cases we have to consider:

1. The completion occurs within a statement block.
    1. For methods that return `void`, we can safely place a semicolon at the end.
    2. For methods that do not return `void`, 90% of the time the user will probably not want to chain them, but we don't want to miss the 10% of the time that the user is writing a chained expression. There are some heuristics we may be able to use here. For example, if a certain function returns an object that is the same type as its parent, then it is probably a method that's desired to be chained. This is how `GLib.StringBuilder` and `Gee.Traversable` methods work.
2. The completion occurs outside of a statement block (passing a variable to a function, as an expression in a lambda, as a default initializer for a parameter, etc). Then we don't want to complete with semicolons.

So as you can see, we want VLS to do the right thing depending on the context. Having a global option for this behavior doesn't work in many cases.

**Comment by benwaffle** [comment]
Once you type `sb.append(`, it autocompletes to `sb.append(|);`, where `|` is your cursor. Then, once you type `"foo")`, your cursor is right before the semicolon, and you can hit `enter` to chain more methods, while keeping the semicolon there.

**Comment by Prince781** [comment]
@benwaffle doing things that way would be simpler. One small problem: VSCode and other editors would treat `;` the same way they do `)`, allowing you to type the exact character without duplicating it. Otherwise, when finished with a statement, the user has to use the arrow keys to get past the semicolon and begin typing a new statement. What does IntelliJ IDEA do?

**Comment by benwaffle** [comment]
@Prince781 The flow i described never requires the user to type a `;`

**Comment by benwaffle** [comment]
but i think you have the same problem with gavr's suggestion / the C# behavior

**Comment by gavr123456789** [comment]
> @benwaffle doing things that way would be simpler. One small problem: VSCode and other editors do not treat `;` the same way they do `)`, allowing you to type the exact character without duplicating it. Otherwise, when finished with a statement, the user has to use the arrow keys to get past the semicolon and begin typing a new statement.
> 
> What does IntelliJ IDEA do?

almost nothing, but I like @benwaffle `sb.append("foo")|;` idea.
![Peek 2020-07-19 23-39](https://user-images.githubusercontent.com/30507409/87884749-42af4f80-ca19-11ea-964b-ec7bed3fee32.gif)

**Comment by gavr123456789** [comment]
I also can't find cases where the semicolon should not be automatically placed after the keywords `continue` and `break`.
