### ISSUE TITLE
MSYS package

### ISSUE THREAD

**Issue by pervoj** [Prince781/vala-language-server#182]
I created fork of this repository for Windows builds. Can you add link to README.md, please?

[https://github.com/pervoj/vala-language-server-windows](https://github.com/pervoj/vala-language-server-windows)

**Comment by pervoj** [comment]
And, small question, why is VLS on Windows opening pkgconfig terminal window after every small code change?

**Comment by gavr123456789** [comment]
@pervoj see https://github.com/Prince781/vala-language-server/issues/120 and https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1662  
you need to use patched glib https://github.com/benwaffle/vala-language-server/files/6332213/mingw-w64-x86_64-glib2-2.68.1-1-any.pkg.tar.zip
(pacman -U pathToFile)

**Comment by pervoj** [comment]
@gavr123456789 Thanks!

**Comment by Prince781** [comment]
While I appreciate your initiative, I think there are much better ways to go about doing this. A few comments:

1. I don't think it's necessary to fork this repo and make releases just quoting the release statements from the main branch. If all you're doing is compiling VLS on Windows, you don't need to go through all this. It would be sufficient to make these releases from an empty repo. Otherwise this may confuse people.
2. Just attaching an `.exe` file to releases doesn't save the Windows user much effort. If they're using Vala in a MSYS environment, there should be a package for VLS. That would be the right way to do it. If they're using Vala in Win32, they've already gone through the hassle of compiling the entire GLib+Vala stack, so it would be little additional effort to compile VLS.

So there you have it. If you want to help out with Windows, the best way to do this would be to make a new package for https://github.com/msys2/MINGW-packages with you as the maintainer. I'm also starting to work on getting Vala build to work on Windows without MSYS2

**Comment by taozuhong** [comment]
@pervoj there are two ways to provide prebuild version for windows:
[MSYS](https://github.com/msys2/MINGW-packages)
[WinGet](https://github.com/microsoft/winget-pkgs)

**Comment by pervoj** [comment]
OK, I will try to package VLS for MSYS2 :)

**Comment by Prince781** [comment]
@pervoj if you need any help ping me on the Vala Discord or here.

**Comment by Prince781** [comment]
@taozuhong will you be submitting your package to https://github.com/msys2/MINGW-packages/ ?

**Comment by taozuhong** [comment]
could you pls release a new version to build MINGW package?

**Comment by Prince781** [comment]
@taozuhong Sure. That will happen soon.

**Comment by pervoj** [comment]
@Prince781 Sorry, but I don't have much time to build a VLS for MSYS2 yet. So I would be happy if @taozuhong would do it. Thanks a lot!

**Comment by Prince781** [comment]
@pervoj Indeed, that's perfectly fine. 😊 I understand some people are busy with certain things.

**Comment by taozuhong** [comment]
@pervoj Honor to do it, and it's convenient for me, because I do it many times in these days.

**Comment by Prince781** [comment]
@taozuhong the release is here: https://github.com/Prince781/vala-language-server/releases/tag/0.48.3

Let me know if there's anything else I can do.

**Comment by taozuhong** [comment]
Got it, the mingw package PR link:
https://github.com/msys2/MINGW-packages/pull/9087

**Comment by pervoj** [comment]
@taozuhong Can you please also build [Prince781/valdo](https://github.com/Prince781/valdo) for MSYS2? Thanks! :)
