### ISSUE TITLE
[Looking for help, Windows] VLS looks to don't recognize namespaces/library

### ISSUE THREAD

**Issue by Miqueas** [Prince781/vala-language-server#216]
I am using VLS on Windows 7 via MSYS and I have the extension for VS Code, but it doesn't seem to work well (see the images).

![image](https://user-images.githubusercontent.com/31262466/131419058-3f5999ca-b4d9-4d79-a4f6-4bc75c3e9908.png)
![image](https://user-images.githubusercontent.com/31262466/131419113-da430741-133a-49f7-924e-19c9cd20b834.png)

I have both libraries in MSYS (plus others like GTK 4), is it possible to solve this? Thank you in advance and I apologize for the inconvenience.

**Comment by Prince781** [comment]
Did you see the notice about using [VLS in the README](https://github.com/Prince781/vala-language-server#editors)?

You need to make sure that your project uses`meson` or has a `compile_commands.json` file in the root folder. Otherwise, if you're editing a single file, you need a shebang at the top (`#/usr/bin/env -S vala --pkg libsoup-2.4 --pkg gxml-0.18`).

**Comment by Miqueas** [comment]
@Prince781 Oh, my mistake, I didn't realize that!

**Comment by Prince781** [comment]
Yeah. This is because Vala is a compiled language, so VLS needs to understand the compiler flags in order to work with your file.

**Comment by Miqueas** [comment]
@Prince781 I see, I use a Lua LS for VS Code so I assumed that works in the same way
